# Adapted from: https://github.com/microsoft/azure-pipelines-tasks/blob/master/.github/workflows/blank.yml
# This action labels and assigns newly opened issues

name: Issue triager
on:
  issues:
    types: [opened]

jobs:
  label:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@50fbc622fc4ef5163becd7fab6573eac35f8462e  # v1

    - uses: damccorm/tag-ur-it@4689c0ef99e78276b2ff4851db5deec57bb3f615  # master
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        configuration-path: "./triage-rules.yml"

    - if: always()
      uses: actions/github-script@83e4cfe60ad25a2d0637965c993eb54c325d6d8d
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        script: |
          github.issues.addLabels({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            labels: ['needs triage']
          })